# Configuration

config:

# MD013 - line-length
  line_length:
    line_length: 120
    code_blocks: false
    tables: false
  html:
    allowed_elements:
      - div

globs:

- "posts/**/*.md"
- "*.md"

ignores:

- "_site/**/*.md"

fix: true
